export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';

export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';

export const UPDATE_TASK_STATUS_SAGA = 'UPDATE_TASK_STATUS_SAGA';

export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';

export const CHANGE_TASK_MODEL = 'CHANGE_TASK_MODEL';

export const CHANGE_ASSIGNESS = 'CHANGE_ASSIGNESS';

export const REMOVE_USER_ASSIGNESS = 'REMOVE_USER_ASSIGNESS';